config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
 root to: 'lists#index'
  resources :lists, only: [:show, :new, :create] do
   resources :bookmarks, only: [:new, :create]
 end
 resources :bookmarks, only: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  #validates :movie, presence: true, uniqueness: { scope: :movie_id, message: 'Must be unique'}
  #validates :list, presence: true, uniqueness: { scope: :list_id, message: 'Must be unique'}
  validates :comment, presence: true, length: { minimum: 6 }
  validates_uniqueness_of :movie_id, scope: [:list_id]
end

app/models/list.rb
class List < ApplicationRecord
    has_many :bookmarks
    has_many :movies, through: :bookmarks, dependent: :destroy 
    validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
    has_many :bookmarks
    validates :title, presence: true, uniqueness: true
    validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
    before_action :set_bookmark, only: :destroy
    before_action :set_list, only: [:new, :create]
    def new
      @bookmark = Bookmark.new
    end
    def create
      @bookmark = Bookmark.new(bookmark_params)
      @bookmark.list = @list
      @bookmark.save
      redirect_to list_path(@list)
    end
    def destroy
      @bookmark.destroy
      redirect_to list_path(@bookmark.list)
    end

    private
    def bookmark_params
      params.require(:bookmark).permit(:comment, :movie_id)
    end
    def set_bookmark
      @bookmark = Bookmark.find(params[:id])
    end
    def set_list
      @list = List.find(params[:list_id])
    end
  end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
    def index
      @lists = List.all
    end
    def show
      @list = List.find(params[:id])
    end
    def new
      @list = List.new
    end
    def create
      @list = List.new(list_params)
      if @list.save
        redirect_to list_path(@list)
      else
        render :new
      end
    end

    private

    def list_params
      params.require(:list).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/new.html.erb
<h1><strong>create new bookmark</strong><h1>

<%= simple_form_for [ @list, @bookmark ] do |f| %>
  <%= f.association :movie %>
  <%= f.input :comment %>
  <%= f.submit "Submit review", class: "btn btn-primary" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  
    <title>RailsWatchList</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/breakfast.jpg)">
  <h1>Save any kind of movies<h1>
</div>
<br>
<br>
<h4>My Lists</h4>
<div class="cards">
  <% @lists.each do |list| %>
  <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/breakfast.jpg)">
    <%= list.name %>
  </div>
  <% end %>
</div>

app/views/lists/new.html.erb
<h1><strong>create new list</strong><h1>
<div>
<%= simple_form_for @list do |m| %>
  <%= m.label :name %>
  <%= m.text_field :name %>
  <%= m.submit %>
<% end %>
</div>

app/views/lists/show.html.erb
<h1><strong><%= @list.name %></strong><h1>

<% @list.bookmarks.each do |bookmark| %>

<div class="cards"  style="width: 24rem; display: inline-block">
  <img class="card-img-top" src="https://picsum.photos/536/354" alt="Card image cap">
  <div class="card-body">
  <h4><strong><%= bookmark.movie.title %></strong></h4>
  <p class="card-text"><%= bookmark.comment %></p>
  </div>
</div>
<% end %>
<br>
<%= link_to "Add new Review", new_list_bookmark_path(@list) %>